"""initial

Revision ID: b10d43c9ba66
Revises:
Create Date: 2025-04-09 22:35:31.988871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b10d43c9ba66"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_event_categories_name"), "event_categories", ["name"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("venue", sa.String(length=255), nullable=False),
        sa.Column("total_tickets", sa.Integer(), nullable=False),
        sa.Column("available_tickets", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("category_id", sa.String(length=100), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["event_categories.name"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_is_published_start_date", "events", ["is_published", "start_date"], unique=False
    )
    op.create_index("idx_start_date_venue", "events", ["start_date", "venue"], unique=False)
    op.create_index(op.f("ix_events_id"), "events", ["id"], unique=False)
    op.create_index(op.f("ix_events_is_published"), "events", ["is_published"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_is_published"), table_name="events")
    op.drop_index(op.f("ix_events_id"), table_name="events")
    op.drop_index("idx_start_date_venue", table_name="events")
    op.drop_index("idx_is_published_start_date", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_event_categories_name"), table_name="event_categories")
    op.drop_table("event_categories")
    # ### end Alembic commands ###
